### ISSUE TITLE
Error: Cannot find module '@notadd/user/services/user.service'

### ISSUE THREAD

**Issue by singee77** [notadd/notadd#297]
`
Singee77-2:notadd singee77$ yarn run:install
yarn run v1.5.1
$ node ./node_modules/@notadd/server/install.js
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module '@notadd/user/entities/user.entity'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/singee77/www/test/php/framework/laravel/notadd/node_modules/@notadd/server/install.js:18:23)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c node ./node_modules/@notadd/server/install.js
Directory: /Users/singee77/www/test/php/framework/laravel/notadd
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/Users/singee77/www/test/php/framework/laravel/notadd/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

`

**Comment by waney** [comment]
同样。

**Comment by waney** [comment]
修改 /@notadd/server/install.js  18行
```const user_entity_1 = require("@notadd/user/model/user.entity");```

**Comment by twilroad** [comment]
错误已经修改完成
