### ISSUE TITLE
快速开始启动notadd报错

### ISSUE THREAD

**Issue by ohsawa-george** [notadd/notadd#312]
nt-rpc-demo、nt-module-use 服务均正常启动，但启动 notadd 时报错
```
(node:92433) UnhandledPromiseRejectionWarning: Error: 2 UNKNOWN: Internal server error
    at Object.exports.createStatusError (/Users/jason/Code/Notadd/notadd/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/jason/Code/Notadd/notadd/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/Users/jason/Code/Notadd/notadd/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/jason/Code/Notadd/notadd/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/jason/Code/Notadd/notadd/node_modules/grpc/src/client_interceptors.js:845:24)
(node:92433) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:92433) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by ohsawa-george** [comment]
数据库设置编码设置问题，已解决！
这个项目很不错，不知能否参与，我们这边也可以考虑资助

**Comment by zuohuadong** [comment]
@ohsawa-george 
感谢支持，欢迎参与。
接受资助，也提供相应的技术服务。

可以加我QQ：1256985886  微信： z2858258

**Comment by dzzzzzy** [comment]
> 数据库设置编码设置问题，已解决！
> 这个项目很不错，不知能否参与，我们这边也可以考虑资助

@ohsawa-george 还考虑参与这个项目吗？

**Comment by DeloDuan** [comment]
数据库编码怎么设置？我改成mysql了。
