### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by dericgit** [notadd/notadd#316]
(node:63449) UnhandledPromiseRejectionWarning: Error: 14 UNAVAILABLE: Connect Failed
    at Object.exports.createStatusError (/Users/derek/Desktop/club/node-workspace/notadd/node_modules/grpc/src/common.js:91:15)
    at Object.onReceiveStatus (/Users/derek/Desktop/club/node-workspace/notadd/node_modules/grpc/src/client_interceptors.js:1204:28)
    at InterceptingListener._callNext (/Users/derek/Desktop/club/node-workspace/notadd/node_modules/grpc/src/client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (/Users/derek/Desktop/club/node-workspace/notadd/node_modules/grpc/src/client_interceptors.js:618:8)
    at callback (/Users/derek/Desktop/club/node-workspace/notadd/node_modules/grpc/src/client_interceptors.js:845:24)
(node:63449) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:63449) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by DeloDuan** [comment]
怎么都是这个错误， 好像没人来解决
